# Generated by Django 2.0.2 on 2018-02-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='desription',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
