# Generated by Django 2.0.2 on 2018-02-07 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Truck RC number')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_mobile', models.IntegerField(blank=True, max_length=20, null=True)),
                ('landline', models.IntegerField(blank=True, max_length=20, null=True)),
                ('video_count', models.IntegerField(blank=True, max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
    ]
