# Generated by Django 2.0.2 on 2018-02-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0002_auto_20180207_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
