# Generated by Django 2.0.2 on 2018-02-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0005_auto_20180208_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='landline',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
