# Generated by Django 2.0.2 on 2018-02-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0006_auto_20180211_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name_plural': 'Audio'},
        ),
    ]
