# Generated by Django 2.0.2 on 2018-03-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0007_auto_20180220_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='logo',
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='album_logo'),
        ),
    ]
