# Generated by Django 2.0.2 on 2018-03-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0008_auto_20180302_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='video',
            name='logo',
        ),
    ]
