# Generated by Django 2.0.2 on 2018-03-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0009_auto_20180302_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='image',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo'),
        ),
        migrations.AddField(
            model_name='video',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='video_logo'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='audio_logo'),
        ),
    ]
