# Generated by Django 2.0.2 on 2018-03-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0011_auto_20180313_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_house.Album'),
        ),
        migrations.AddField(
            model_name='video',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_house.Album'),
        ),
    ]
