# Generated by Django 2.0.2 on 2018-02-07 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Truck RC number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.FloatField(blank=True, max_length=20, null=True)),
                ('old_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
    ]
