# Generated by Django 2.0.2 on 2018-02-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20180207_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='old_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
