# Generated by Django 2.0.2 on 2018-02-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20180211_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpassword',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
