# Generated by Django 2.0.2 on 2018-03-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customerpassword_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
    ]
