# Generated by Django 2.0.2 on 2018-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage='storages.backends.s3boto3.S3Boto3Storage', upload_to='user_photo'),
        ),
    ]
